//
//  myperson.m
//  RouleDemo
//
//  Created by liwenhua on 2019/12/23.
//  Copyright © 2019 李文华. All rights reserved.
//

#import "myperson.h"

@implementation myperson

- (void)makeSubviews{
    
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")
    NSLog(@"ddddd")

}


- (void)demo{ }
- (void)demo1{ }
- (void)demo2{ }
- (void)demo3{ }
- (void)demo4{ }
- (void)demo5{ }
- (void)demo6{ }
- (void)demo7{ }
- (void)demo8{ }
- (void)demo9{ }
- (void)demo10{ }
- (void)demo11{ }
- (void)demo12{ }
- (void)demo13{ }
- (void)demo14{ }
- (void)demo15{ }
- (void)demo16{ }
- (void)demo17{ }
- (void)demo18{ }
- (void)demo19{ }
- (void)demo20{ }
- (void)demo21{ }
- (void)demo22{ }
- (void)demo23{ }



@end
